joy:
    deadzone : 0.05
    frequency: 80.0 # msg/sec

    steering_axis: 3 # Right Joystick
    speed_axis: 2 # Left Trigger
    acceleration_axis: 2 # Left Trigger
    brake_axis: 5 # Right Trigger
    switch_mode: 0 # BUtton 'A'
    switch_direciton: 4 # Left Bump
    
    speed_scale: 5 # meter/sec
    acceleration_scale: 1 # meter/sec^2
