asimcar:
    mass: 10 # kg
    wheelbase: .256 # meter
    wheel_radius: 0.0265 # meter
    gear_ratio: 6.87

vesc:
    smooth_rate: 80.0

    # erpm (electrical rpm) = speed_to_erpm_gain * speed (m/s) + erpm_offset
    max_acceleration: 3.5 # m/s^2
    speed_to_erpm_gain: 1988 # m/s -> rpm
    erpm_offset: 0.0 # rpm

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering_angle (radians) + servo_offset
    max_servo_speed: 3.2 # rad/sec
    steering_angle_to_servo_gain: -1.0472 # rad -> servo value
    servo_offset: 0.58 # servo value

    # current = mass * wheel_radius * 4 / gear_ratio / torque_constant * acceleration (m/s^2)+ current_offset
    max_jerk: 3.2 # m/s^3
    torque_constant: 3500 # kV

    tachometer_ticks_to_meters_gain: 0.00225
    # publish odom to base link tf
    vesc_to_odom/publish_tf: false

    vesc_driver:
        port: /dev/VESC
        duty_cycle_min: 0.0
        duty_cycle_max: 1.0
        current_min: 0.0
        current_max: 80
        brake_min: -20000.0
        brake_max: 200000.0
        speed_min: -4000
        speed_max: 4000
        position_min: 0.0
        position_max: 0.0
        servo_min: 0
        servo_max: 1
